"""
Phase 10 - Price Sensitivity & Break-even Elasticity (B3)

WHAT THIS PHASE REFUSES TO DO
-----------------------------
It does not estimate a price elasticity. `net_price_sim` is generated by the phase-6 rules -
promotion depth (R4), the store price index (R3) and inflation drift (R2). Regressing observed
quantities on those prices recovers the rules we wrote, not customer behaviour. A number would
come out, it would look like an elasticity, and it would be circular.

WHAT IT DOES INSTEAD
--------------------
B3-1  Break-even analysis. How much volume a price change could afford to lose (or would have
      to gain) for gross margin to stay flat. This needs NO behavioural assumption at all - it
      follows from the margin structure:

          Q(P - C) = Q'[P(1+x) - C],  with C = P(1-m)   =>   Q'/Q = m / (m + x)

B3-2  Elasticity sensitivity. Three EXPLICIT assumptions (-1.0, -1.5, -2.0) run through the
      full chain: new volume -> revenue -> COGS -> gross margin -> change vs baseline. These
      are stated assumptions, never estimates. Rows whose new price falls below unit cost are
      flagged `below_cost`, never silently dropped.

B3-3  Methodological guardrail. The price/volume regression inside the scenario is computed
      and kept - as a demonstration of the circularity, in a file named `diagnostic_...` and
      documented under a guardrail heading in docs/23. It is deliberately absent from the KPI
      outputs, however interesting the coefficient looks.

Baseline comes from phase 9 (fulfilled quantity, canonical since B2).

Outputs:
  data/processed/kpi_break_even_elasticity_sim.csv
  data/processed/kpi_price_scenario_sim.csv
  data/processed/diagnostic_price_volume_regression_sim.csv
  reports/price_sensitivity_sim.md
"""
import os
import shutil

import numpy as np
import pandas as pd

import audit
import schema

ROOT = os.path.join(os.path.dirname(__file__), "..")
PROCESSED = os.path.join(ROOT, "data", "processed")
REPORTS = os.path.join(ROOT, "reports")
LOCAL = "/tmp/price_sensitivity"
os.makedirs(LOCAL, exist_ok=True)

PRICE_GRID = [-0.20, -0.15, -0.10, -0.05, -0.02, 0.02, 0.05, 0.10, 0.15, 0.20]
ELASTICITY_ASSUMPTIONS = [-1.0, -1.5, -2.0]


def break_even(base):
    """B3-1: no behavioural assumption - pure margin arithmetic."""
    rows = []
    for r in base.itertuples():
        for x in PRICE_GRID:
            m = r.margin_rate_sim
            denom = m + x
            feasible = denom > 0
            ratio = (m / denom) if feasible else np.nan
            new_price = r.avg_net_price_sim * (1 + x)
            rows.append({
                "family": r.family,
                "price_change_pct": round(100 * x, 2),
                "baseline_units_sim": r.baseline_units_sim,
                "baseline_revenue_sim": r.baseline_revenue_sim,
                "baseline_margin_sim": r.baseline_margin_sim,
                "margin_rate_sim": m,
                "avg_net_price_sim": r.avg_net_price_sim,
                "avg_unit_cost_sim": r.avg_unit_cost_sim,
                "new_price_sim": new_price,
                "break_even_volume_ratio_sim": ratio,
                "break_even_volume_change_pct_sim": (100 * (ratio - 1)) if feasible else np.nan,
                "feasibility_flag": "feasible" if feasible else "margin_cannot_be_restored",
                "below_cost_flag": bool(new_price <= r.avg_unit_cost_sim),
            })
    return pd.DataFrame(rows)


def scenarios(base):
    """B3-2: explicit elasticity ASSUMPTIONS, constant-elasticity form Q'/Q = (1+x)^e."""
    rows = []
    for r in base.itertuples():
        for x in PRICE_GRID:
            for e in ELASTICITY_ASSUMPTIONS:
                ratio = (1 + x) ** e
                new_price = r.avg_net_price_sim * (1 + x)
                new_units = r.baseline_units_sim * ratio
                new_revenue = new_units * new_price
                new_cogs = new_units * r.avg_unit_cost_sim      # unit cost held constant
                new_margin = new_revenue - new_cogs
                rows.append({
                    "family": r.family,
                    "price_change_pct": round(100 * x, 2),
                    "elasticity_assumption": e,
                    "baseline_units_sim": r.baseline_units_sim,
                    "baseline_revenue_sim": r.baseline_revenue_sim,
                    "baseline_margin_sim": r.baseline_margin_sim,
                    "new_price_sim": new_price,
                    "volume_ratio_sim": ratio,
                    "new_units_sim": new_units,
                    "new_revenue_sim": new_revenue,
                    "new_cogs_sim": new_cogs,
                    "new_margin_sim": new_margin,
                    "revenue_change_vs_baseline_pct": 100 * (new_revenue / r.baseline_revenue_sim - 1),
                    "margin_change_vs_baseline_pct": 100 * (new_margin / r.baseline_margin_sim - 1),
                    "below_cost_flag": bool(new_price <= r.avg_unit_cost_sim),
                })
    return pd.DataFrame(rows)


def diagnostic_regression():
    """B3-3: kept ONLY to demonstrate why this is not elasticity evidence."""
    df = schema.read_table("fact_sales_commercial.parquet", PROCESSED,
                           columns=["family", "units", "net_price_sim"])
    df = df[(df["units"] > 0) & (df["net_price_sim"] > 0)]
    out = []
    for fam, g in df.groupby("family", observed=True):
        lp, lq = np.log(g["net_price_sim"].to_numpy(dtype="float64")), np.log(g["units"].to_numpy(dtype="float64"))
        slope, intercept = np.polyfit(lp, lq, 1)
        pred = intercept + slope * lp
        ss_res = float(((lq - pred) ** 2).sum())
        ss_tot = float(((lq - lq.mean()) ** 2).sum())
        out.append({
            "family": str(fam),
            "n_rows": int(len(g)),
            "log_log_slope": float(slope),
            "r_squared": float(1 - ss_res / ss_tot) if ss_tot else np.nan,
            "interpretation_warning": ("NOT an elasticity estimate: price variation is generated "
                                       "by the phase-6 rules, so this slope reflects the scenario "
                                       "construction, not customer behaviour"),
        })
    return pd.DataFrame(out)


def main():
    kpi = schema.read_table("kpi_pricing_sim.csv", PROCESSED)
    # Average price and cost are recomputed from the totals rather than read from the
    # rounded per-unit columns of the KPI file. The break-even ratio m/(m+x) has a tiny
    # denominator when the price cut approaches the margin, so a third-decimal rounding in
    # the price would be amplified into a double-digit error - and the round-trip audit
    # below would (correctly) refuse it. Deriving p and c from the totals keeps
    # m = (p - c) / p true by construction.
    base = pd.DataFrame({
        "family": kpi["family"],
        "baseline_units_sim": kpi["fulfilled_units_sim"],
        "baseline_revenue_sim": kpi["revenue_sim"],
        "baseline_margin_sim": kpi["gross_margin_sim"],
        "margin_rate_sim": kpi["gross_margin_sim"] / kpi["revenue_sim"],
        "avg_net_price_sim": kpi["revenue_sim"] / kpi["fulfilled_units_sim"],
        "avg_unit_cost_sim": kpi["cogs_sim"] / kpi["fulfilled_units_sim"],
    })
    print("baseline families:", len(base))

    be = break_even(base)
    audit.assert_break_even_roundtrip(be)
    print("break-even audit passes: applying the break-even volume ratio restores the "
          "baseline margin exactly (etl/audit.py)")

    sc = scenarios(base)
    diag = diagnostic_regression()

    schema.write_table(be, "kpi_break_even_elasticity_sim.csv", PROCESSED, LOCAL)
    schema.write_table(sc, "kpi_price_scenario_sim.csv", PROCESSED, LOCAL)
    schema.write_table(diag, "diagnostic_price_volume_regression_sim.csv", PROCESSED, LOCAL)

    # ---------------- report ----------------
    chain_m = base["baseline_margin_sim"].sum() / base["baseline_revenue_sim"].sum()
    chain = pd.DataFrame({"price_change_pct": [round(100 * x, 1) for x in PRICE_GRID]})
    chain["break_even_volume_change_pct"] = [
        round(100 * (chain_m / (chain_m + x) - 1), 1) if chain_m + x > 0 else np.nan
        for x in PRICE_GRID]

    thin = base.nsmallest(3, "margin_rate_sim")["family"].tolist()
    wide = base.nlargest(3, "margin_rate_sim")["family"].tolist()
    disc10 = be[(be["price_change_pct"] == -10.0)
                & (be["family"].isin(thin + wide))][
        ["family", "margin_rate_sim", "break_even_volume_change_pct_sim", "feasibility_flag"]]
    disc10 = disc10.assign(margin_rate_sim=(100 * disc10["margin_rate_sim"]).round(1),
                           break_even_volume_change_pct_sim=disc10[
                               "break_even_volume_change_pct_sim"].round(1))

    trade = sc[(sc["elasticity_assumption"] == -1.5) & (sc["price_change_pct"] == 5.0)][
        ["family", "revenue_change_vs_baseline_pct", "margin_change_vs_baseline_pct"]].round(1)
    both_ways = trade[(trade["revenue_change_vs_baseline_pct"] < 0)
                      & (trade["margin_change_vs_baseline_pct"] > 0)]

    lines = [
        "# Price Sensitivity & Break-even Analysis — simulated commercial scenario",
        "",
        "Every monetary figure here is **simulated** (`docs/19_Simulation_Design.md`). This page",
        "contains **no estimate of customer price elasticity**, and the reason is in §3.",
        "",
        "## 1. Break-even analysis (no behavioural assumption)",
        "",
        "How much volume a price change could afford to lose, or would have to gain, for gross",
        "margin to stay flat: `Q'/Q = m / (m + x)`. This is margin arithmetic, not a forecast.",
        "",
        "Chain level, at a simulated gross margin of %.1f%%:" % (100 * chain_m),
        "",
        chain.to_markdown(index=False),
        "",
        "A positive number is volume that must be **gained**, a negative number is volume that",
        "can be **lost** while margin holds.",
        "",
        "### The finding that matters",
        "",
        "Break-even depends entirely on the starting margin, so a discount is a completely",
        "different proposition per category. At a 10% price cut:",
        "",
        disc10.to_markdown(index=False),
        "",
        "For the thin-margin staples a 10% discount needs the volume to roughly double before it",
        "pays for itself. For wide-margin categories the same discount is far easier to justify.",
        "That is a pricing decision rule which needs no elasticity estimate at all.",
        "",
        "## 2. Elasticity sensitivity (explicit assumptions)",
        "",
        "Three assumed elasticities (−1.0, −1.5, −2.0) run through volume → revenue → COGS →",
        "margin, using `Q'/Q = (1+x)^e` and holding unit cost constant. **These are assumptions,",
        "not estimates.** Rows whose new price would fall below unit cost are flagged",
        "`below_cost` and kept, never silently dropped.",
        "",
        "The trade-off a pricing analyst actually decides on is revenue against margin: at a 5%",
        "price increase with an assumed elasticity of −1.5, %d of %d families lose revenue while"
        % (len(both_ways), len(trade)),
        "gaining gross margin.",
        "",
        "Full grid: `data/processed/kpi_price_scenario_sim.csv`",
        "(%d rows = %d families × %d price steps × %d assumptions)."
        % (len(sc), len(base), len(PRICE_GRID), len(ELASTICITY_ASSUMPTIONS)),
        "",
        "## 3. Methodological guardrail — why there is no elasticity estimate here",
        "",
        "The observed relationship between simulated prices and observed quantities is",
        "**mechanically contaminated by the scenario construction** and must not be interpreted",
        "as an estimate of customer price elasticity.",
        "",
        "Prices in this project are generated by the phase-6 rules: promotion depth (R4), the",
        "store price index (R3) and inflation drift (R2). A log-log regression of quantity on",
        "those prices therefore recovers the rules, not behaviour — the discount is deep",
        "*because* the promotion is large, and the volume is high *because* the promotion is",
        "large. The slope is an artefact of that shared cause.",
        "",
        "The regression is computed anyway and kept in",
        "`data/processed/diagnostic_price_volume_regression_sim.csv`, as a demonstration rather",
        "than a result. It appears in no KPI output and in no dashboard, however plausible the",
        "coefficients look. Details: `docs/23_Price_Sensitivity_Design.md` §4.",
        "",
    ]
    path = os.path.join(LOCAL, "price_sensitivity_sim.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    shutil.copyfile(path, os.path.join(REPORTS, "price_sensitivity_sim.md"))

    print("\n--- price sensitivity summary (simulated) ---")
    print("chain margin rate    : %.1f%%" % (100 * chain_m))
    print("break-even at +5%%    : volume may fall %.1f%%"
          % abs(100 * (chain_m / (chain_m + 0.05) - 1)))
    print("break-even at -10%%   : volume must rise %.1f%%"
          % (100 * (chain_m / (chain_m - 0.10) - 1)))
    print("break-even rows      : %d (%d not restorable, %d below cost)"
          % (len(be), (be["feasibility_flag"] != "feasible").sum(), be["below_cost_flag"].sum()))
    print("scenario rows        : %d (%d below cost, kept and flagged)"
          % (len(sc), sc["below_cost_flag"].sum()))
    print("diagnostic slopes    : %.2f to %.2f  <- NOT elasticities, see docs/23 §4"
          % (diag["log_log_slope"].min(), diag["log_log_slope"].max()))
    print("\nwritten to %s and reports/" % PROCESSED)


if __name__ == "__main__":
    main()
